#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ms-buildah
Version  : 1.9.1
Release  : 1
URL      : https://github.com/containers/buildah/archive/v1.9.1.tar.gz
Source0  : https://github.com/containers/buildah/archive/v1.9.1.tar.gz
Summary  : Builds Dockerfile using the Docker client
Group    : Development/Tools
License  : Apache-2.0 GPL-3.0
BuildRequires : buildreq-golang

%description
Builds Dockerfile using the Docker client

%prep
%setup -q -n buildah-1.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
go build

%install
rm -rf %{buildroot}


%files
%defattr(-,root,root,-)
